import {useEffect,useId,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {CircleHelp} from 'lucide-react';
export default function FieldHelp({text,label}:{text:string;label:string}) {
 const [mounted,setMounted]=useState(false),[visible,setVisible]=useState(false),[pos,setPos]=useState({left:0,top:0});
 const trigger=useRef<HTMLButtonElement>(null),box=useRef<HTMLDivElement>(null),enter=useRef<ReturnType<typeof setTimeout>|null>(null),leave=useRef<ReturnType<typeof setTimeout>|null>(null);const id=useId();
 const clear=()=>{if(enter.current)clearTimeout(enter.current);if(leave.current)clearTimeout(leave.current)};
 const hide=()=>{clear();setVisible(false);leave.current=setTimeout(()=>setMounted(false),140)};
 const show=()=>{clear();window.dispatchEvent(new CustomEvent('tc:tooltip-open',{detail:id}));enter.current=setTimeout(()=>{setMounted(true);requestAnimationFrame(()=>setVisible(true))},35)};
 useLayoutEffect(()=>{if(!mounted||!trigger.current)return;const r=trigger.current.getBoundingClientRect(),height=box.current?.offsetHeight??100;setPos({left:Math.max(8,Math.min(r.left,window.innerWidth-312)),top:r.bottom+height+8<window.innerHeight?r.bottom+6:Math.max(8,r.top-height-6)})},[mounted,text]);
 useEffect(()=>{const other=(e:Event)=>{if((e as CustomEvent).detail!==id)hide()};const dismiss=()=>hide();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')hide()};window.addEventListener('tc:tooltip-open',other);window.addEventListener('tc:hide-tooltips',dismiss);window.addEventListener('scroll',dismiss,true);window.addEventListener('resize',dismiss);window.addEventListener('blur',dismiss);document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',key);return()=>{clear();window.removeEventListener('tc:tooltip-open',other);window.removeEventListener('tc:hide-tooltips',dismiss);window.removeEventListener('scroll',dismiss,true);window.removeEventListener('resize',dismiss);window.removeEventListener('blur',dismiss);document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',key)}},[id]);
 return <><button type="button" ref={trigger} aria-label={`Справка: ${label}`} aria-describedby={mounted?id:undefined} className="no-drag shrink-0 rounded p-0.5 text-text-faint transition-colors hover:text-accent" onPointerEnter={show} onPointerLeave={hide} onFocus={show} onBlur={hide} onClick={show}><CircleHelp size={12}/></button>{mounted&&createPortal(<div id={id} ref={box} role="tooltip" className="pointer-events-none fixed z-[150] w-[304px] rounded-lg border border-border bg-surface-2 p-3 text-xs leading-relaxed text-text shadow-xl motion-reduce:transition-none" style={{...pos,opacity:visible?1:0,transform:`translateY(${visible?0:3}px)`,transition:'opacity 140ms ease, transform 140ms ease'}}>{text}</div>,document.body)}</>
}
