#!/usr/bin/env bash
# Regenerates third_party/todaycore: TodayCore's changes rebased onto the
# sing-box version the app links, published under its own module path.
#
# Why this exists. TodayCore (github.com/TumGovic/TodayCore) is a patch set on
# top of sing-box and keeps sing-box's module path, github.com/sagernet/sing-box.
# Go allows one version per module path in a build, so it cannot sit next to
# upstream sing-box as is. And both have to share the sagernet/sing* dependency
# modules, whose APIs move between sing-box releases — linking TodayCore's own
# base (1.15.0-alpha.6) next to a newer sing-box fails to compile.
#
# So the tree is rebuilt: upstream sing-box at exactly the version in go.mod,
# with every file TodayCore added copied in and every file it modified merged
# three-way (TodayCore's base → TodayCore, applied onto the target release),
# then the module is renamed to github.com/tumgovic/todaycore.
#
# Usage: bash scripts/sync-todaycore.sh [todaycore-ref] [todaycore-base]
#   todaycore-ref   git ref of TodayCore to take (default: main)
#   todaycore-base  sing-box release TodayCore is based on (default: v1.15.0-alpha.6)
set -euo pipefail

REPO_URL="https://github.com/TumGovic/TodayCore"
REF="${1:-main}"
BASE="${2:-v1.15.0-alpha.6}"
NEW_MODULE="github.com/tumgovic/todaycore"
OLD_MODULE="github.com/sagernet/sing-box"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/third_party/todaycore"
TARGET="$(cd "$ROOT" && go list -m -f '{{.Version}}' "$OLD_MODULE")"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "TodayCore $REF (base $BASE) -> sing-box $TARGET"

git -c core.autocrlf=false clone --quiet "$REPO_URL" "$WORK/tc"
git -C "$WORK/tc" -c advice.detachedHead=false checkout --quiet "$REF"
TC_COMMIT="$(git -C "$WORK/tc" rev-parse HEAD)"
TC_VERSION="$(git -C "$WORK/tc" describe --tags --always)"

moddir() { (cd "$ROOT" && go mod download -json "$OLD_MODULE@$1") | sed -n 's/.*"Dir": "\(.*\)",/\1/p' | sed 's#\\\\#/#g'; }
BASE_DIR="$(moddir "$BASE")"
TARGET_DIR="$(moddir "$TARGET")"

# What goes into the tree: library code only. The CLI, docs, integration tests
# and release tooling are not linked into the app.
keep() {
  case "$1" in
    cmd/*|docs/*|test/*|release/*|clients/*|.github/*) return 1 ;;
    *_test.go) return 1 ;;
  esac
  return 0
}

rm -rf "$OUT"
mkdir -p "$OUT"

# 1. The target release as the starting point.
(cd "$TARGET_DIR" && find . -type f | sed 's#^\./##') | while read -r f; do
  keep "$f" || continue
  mkdir -p "$OUT/$(dirname "$f")"
  cp "$TARGET_DIR/$f" "$OUT/$f"
done
chmod -R u+w "$OUT"

# 2. TodayCore's own changes relative to its base.
(cd "$WORK/tc" && git ls-files) | while read -r f; do
  keep "$f" || continue
  case "$f" in *.go|go.mod) ;; *) continue ;; esac
  tc="$WORK/tc/$f"
  if [ ! -f "$BASE_DIR/$f" ]; then
    mkdir -p "$OUT/$(dirname "$f")"
    cp "$tc" "$OUT/$f"
    echo "  added    $f"
  elif ! cmp -s "$tc" "$BASE_DIR/$f"; then
    [ "$f" = go.mod ] && continue # dependency versions are settled by the app's go.mod
    if [ ! -f "$OUT/$f" ]; then
      echo "  CONFLICT $f (removed upstream)"; echo "$f" >> "$WORK/conflicts"; continue
    fi
    cp "$tc" "$WORK/merged"
    if git merge-file -q "$WORK/merged" "$BASE_DIR/$f" "$OUT/$f"; then
      echo "  merged   $f"
    else
      echo "  CONFLICT $f"; echo "$f" >> "$WORK/conflicts"
    fi
    cp "$WORK/merged" "$OUT/$f"
  fi
done

# 3. Own protobuf namespace: the .proto files are sing-box's own, and Go's
#    global protobuf registry refuses the same file registered twice. Runs
#    before the text replace below, which would corrupt the length-prefixed
#    strings inside the serialized descriptors.
(cd "$ROOT" && go run scripts/protorename/main.go "$OUT" todaycore "$OLD_MODULE" "$NEW_MODULE")

# 4. Own module path, so it links next to upstream sing-box.
find "$OUT" -type f \( -name '*.go' -o -name go.mod \) -print0 |
  xargs -0 sed -i "s#$OLD_MODULE\\b#$NEW_MODULE#g"
rm -f "$OUT/go.sum"

# The app shows these on the About screen; build info only sees a replaced
# module without a version.
cat > "$OUT/constant/todaycore.go" <<EOF
// Code generated by scripts/sync-todaycore.sh. DO NOT EDIT.

package constant

const (
	TodayCoreVersion = "${TC_VERSION#v}"
	TodayCoreCommit  = "$TC_COMMIT"
	TodayCoreBase    = "${TARGET#v}"
)
EOF

cat > "$OUT/TODAYCORE_VERSION" <<EOF
TodayCore $TC_VERSION $TC_COMMIT ($REPO_URL, ref $REF)
TodayCore base: sing-box $BASE
Rebased onto:   sing-box $TARGET
Module path:    $NEW_MODULE
Generated by scripts/sync-todaycore.sh — do not edit by hand.
EOF

if [ -s "$WORK/conflicts" ]; then
  echo "resolve by hand (conflict markers are left in place):"; cat "$WORK/conflicts"
  exit 1
fi
echo "done: $OUT"
