// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function CollectGarbage() {
  return window['go']['main']['App']['CollectGarbage']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function ExportHeapProfile() {
  return window['go']['main']['App']['ExportHeapProfile']();
}

export function ExportRouting() {
  return window['go']['main']['App']['ExportRouting']();
}

export function GetActiveProfileJSON() {
  return window['go']['main']['App']['GetActiveProfileJSON']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetCoreIssues() {
  return window['go']['main']['App']['GetCoreIssues']();
}

export function GetCores() {
  return window['go']['main']['App']['GetCores']();
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function GetGoroutineDump() {
  return window['go']['main']['App']['GetGoroutineDump']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfileCores(arg1) {
  return window['go']['main']['App']['GetProfileCores'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRuntimeStats() {
  return window['go']['main']['App']['GetRuntimeStats']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsJSON() {
  return window['go']['main']['App']['GetSettingsJSON']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function ImportLinks(arg1) {
  return window['go']['main']['App']['ImportLinks'](arg1);
}

export function ImportRouting() {
  return window['go']['main']['App']['ImportRouting']();
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function PingLatency(arg1) {
  return window['go']['main']['App']['PingLatency'](arg1);
}

export function PingProfile(arg1) {
  return window['go']['main']['App']['PingProfile'](arg1);
}

export function PreviewConfig() {
  return window['go']['main']['App']['PreviewConfig']();
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RunNetDiag() {
  return window['go']['main']['App']['RunNetDiag']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveProfileJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileJSON'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowUpdateFolder() {
  return window['go']['main']['App']['ShowUpdateFolder']();
}

export function SimulateStatus(arg1) {
  return window['go']['main']['App']['SimulateStatus'](arg1);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}

export function SubscriptionHeaders() {
  return window['go']['main']['App']['SubscriptionHeaders']();
}

export function TestProfileSpeed(arg1) {
  return window['go']['main']['App']['TestProfileSpeed'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
