// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function AddSubscription(arg1:string,arg2:string):Promise<model.Subscription>;

export function ClearLogs():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetLogs():Promise<Array<string>>;

export function GetProfiles():Promise<Array<model.Profile>>;

export function GetSettings():Promise<model.AppSettings>;

export function GetStatus():Promise<model.Status>;

export function GetSubscriptions():Promise<Array<model.Subscription>>;

export function ImportLink(arg1:string):Promise<model.Profile>;

export function SaveProfile(arg1:model.Profile):Promise<void>;

export function SaveSettings(arg1:model.AppSettings):Promise<void>;

export function UpdateSubscription(arg1:string):Promise<model.Subscription>;
