// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';
import {cores} from '../models';
import {device} from '../models';

export function AddSubscription(arg1:string,arg2:string):Promise<model.Subscription>;

export function ClearLogs():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ExportDiagnostics():Promise<string>;

export function GetActiveProfileJSON():Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCoreIssues():Promise<Record<string, string>>;

export function GetCores():Promise<Array<cores.Info>>;

export function GetDeviceInfo():Promise<device.Info>;

export function GetLogs():Promise<Array<string>>;

export function GetProfileCores(arg1:string):Promise<main.ProfileCores>;

export function GetProfiles():Promise<Array<model.Profile>>;

export function GetSettings():Promise<model.AppSettings>;

export function GetSettingsJSON():Promise<string>;

export function GetStatus():Promise<model.Status>;

export function GetSubscriptions():Promise<Array<model.Subscription>>;

export function ImportLinks(arg1:string):Promise<Array<model.Profile>>;

export function ListProcesses():Promise<Array<main.ProcessInfo>>;

export function PingLatency(arg1:string):Promise<number>;

export function PingProfile(arg1:string):Promise<main.PingResult>;

export function PreviewConfig():Promise<string>;

export function ResetAllData():Promise<void>;

export function ResetSettings():Promise<void>;

export function RunNetDiag():Promise<string>;

export function SaveProfile(arg1:model.Profile):Promise<void>;

export function SaveProfileJSON(arg1:string,arg2:string):Promise<model.Profile>;

export function SaveSettings(arg1:model.AppSettings):Promise<void>;

export function SimulateStatus(arg1:string):Promise<void>;

export function StopSimulation():Promise<void>;

export function SubscriptionHeaders():Promise<Record<string, string>>;

export function UpdateSubscription(arg1:string):Promise<model.Subscription>;
