// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function GetActiveProfileJSON() {
  return window['go']['main']['App']['GetActiveProfileJSON']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsJSON() {
  return window['go']['main']['App']['GetSettingsJSON']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function ImportLink(arg1) {
  return window['go']['main']['App']['ImportLink'](arg1);
}

export function ListProcesses() {
  return window['go']['main']['App']['ListProcesses']();
}

export function PingLatency(arg1) {
  return window['go']['main']['App']['PingLatency'](arg1);
}

export function PingProfile(arg1) {
  return window['go']['main']['App']['PingProfile'](arg1);
}

export function PreviewConfig() {
  return window['go']['main']['App']['PreviewConfig']();
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RunNetDiag() {
  return window['go']['main']['App']['RunNetDiag']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SimulateStatus(arg1) {
  return window['go']['main']['App']['SimulateStatus'](arg1);
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
